server:
  port: 8003 # 服务端口
spring:
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
  profiles:
    active: dev # 环境设置：dev、test、prod
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 10240MB # 最大置总上传的数据大小 ：默认10M
#阿里云 vod
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      keyid: LTAI4G6nQKLV4c9EvTrFzJcV
      keysecret: PRcfxXfqk9gwPQFiNvepJ1l7oUkqy7
