server:
  port: 8150 # 服务端口
spring:
  application:
    name: service-ucenter # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql数据库连接
    url: jdbc:mysql://localhost:3306/lwzxlm?serverTimezone=GMT%2B8
    password: root
    username: root
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0 #最小空闲
wx:
  open:
    app_id: wxed9954c01bb89b47 # 微信开放平台 appid
    app_secret: a7482517235173ddb4083788de60b90e # 微信开放平台 appsecret
    redirect_url: http://guli.shop/api/ucenter/wx/callback # 微信开放平台 重定向url
mybatis-plus:
  mapper-locations: classpath:com/atguigu/educenter/mapper/xml/*.xml #配置mapper xml文件的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
