server:
  port: 8002 #服务端口
spring:
  application:
    name: service-oss #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
  profiles:
    active: dev #环境设置：dev、test、prod
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4G6nQKLV4c9EvTrFzJcV
      keysecret: PRcfxXfqk9gwPQFiNvepJ1l7oUkqy7
      bucketname: edu-guli-1010 #bucket可以在控制台创建，也可以使用java代码创建
